from setuptools import setup, find_packages

setup(
    name='mechdesignagents',
    version='0.1.0',
    license="Apache Public License 2.0",
    author="Nirmal Prasad Panta",
    author_email="nirmal@ank-world.com",
    description="MechDesign agents generates CAD model using LLMs.",
    packages=find_packages(exclude=("tests",)),
    install_requires=[
        'autogen',
        'cadquery',
        'ocp_vscode',
        'chromadb',
        'streamlit',
        'fenics',
        'matplotlib',
        'numpy',
        'scipy',
        'sympy',
        'requests',
        'pydantic',
        'typing_extensions',
        'openai',
        'langchain',
        'pinecone-client',
        'transformers',
        'sentence_transformers',
        'fastapi',
        'uvicorn',
        'python-multipart',
        'Pillow',
    ]
)